# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
