# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 4, 9, 13, 21, 630125, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
