language: python

python:
  - "3.6"

sudo: required

dist: trusty

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - flake8 ;

after_script:
  - killall -9 python


