# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20180705_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='suscribed',
            new_name='subscribed',
        ),
    ]
